### ISSUE TITLE
Convert old repository to bookdown format.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#1]
- [x] Add one file per chapter, appendix, etc.
    - [x] Update chapters that can be updated
    - [x] Create new Issues as needing
- [x] Update README.
- [x] Do not add sensitive documents.
- [x] Add LICENSE.
- [x] Add .github folder with ISSUE/PR templates
- [x] Add custom _vallenderlab_ CODE_OF_CONDUCT.

**Note**:  Do not reformat until the end of writing to eliminate needless formatting/reformatting.
**Note**:  Do not commit build until later.

**Comment by sdhutchins** [comment]
Great idea. I've been thinking about this.

**Comment by grabear** [comment]
It seemed a little late to get started on MicrobiomeR again, so I figured this would be productive.

**Comment by sdhutchins** [comment]
Should we keep this repo private so we can include more "sensitive" protocols?

**Comment by grabear** [comment]
I thought we could use this one as a public version for the website.  That way we can have items here that we can browse online in addition to all of the scripting we have.

**Comment by grabear** [comment]
For non-sensitive templates, we can figure out how to host them and in the docs maybe we can link to them??  @sdhutchins

**Comment by sdhutchins** [comment]
> I thought we could use this one as a public version for the website. That way we can have items here that we can browse online in addition to all of the scripting we have.


> For non-sensitive templates, we can figure out how to host them and in the docs maybe we can link to them?? @sdhutchins

I like that idea! We can provide a link to supplemental docs or something of that variety.
